services:
  camoufox:
    build: .
    ports:
      - "5345:5345"
    environment:
      # 设置一个你最终Gemini服务的API密钥
      - AUTH_API_KEY=5122
    volumes:
      - ./camoufox-py/config.yaml:/app/config.yaml
      - ./camoufox-py/cookies:/app/cookies
      - ./camoufox-py/logs:/app/logs
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNTc4Y2YzZWRkNDZmM2ZkOGMxMzI3MDI5YWY5N2VjYWYiLCJ0IjoiYTVlOTM5NjUtYTc2ZC00MzI2LWE1MTItMzA4ZDQ0YTNiYWQ5IiwicyI6Ik1URmxaamczTnpRdE5qTmxZaTAwWWprMkxUaGxOek10WWpJeVlUazFaVGMwTlRVMiJ9
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    restart: always
    depends_on:
      - camoufox
