[supervisord]
nodaemon=true ; 让 Supervisor 在前台运行，以保持容器存活

[program:go_app]
command=/app/go_app_binary
directory=/app ; 
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHON_BIN="python3",SCRIPT_DIR="/app",CONFIG_PATH="/app/config.yaml",COOKIES_DIR="/app/cookies"
